### PR TITLE
For publication/deploy on Thursday 8 December 2022

### PR DESCRIPTION
**Pull request by alflennik**
Hi @shawna-slh and @SteveALee, this PR includes the content we would like to deploy tomorrow on December 8, 2022.

The deploy will include support for aria-practices' new [content reorganization](https://github.com/w3c/aria-practices/issues/2418) which was [merged today](https://github.com/w3c/aria-practices/pull/2417). The main changes to wai-aria-practices are below:
- [Support content rearchitecture](https://github.com/w3c/wai-aria-practices/pull/170)
- [Address ARIA Practices PR 2417 Feedback](https://github.com/w3c/wai-aria-practices/pull/173)

It should be released simultaneously with redirects from the previous URLs to new URLs, which will be handled by @deniak (see https://github.com/w3c/wai-aria-practices/issues/172 for more information).

Preview of how the site should appear is here: [aria-practices.netlify.app/aria/apg/](https://aria-practices.netlify.app/aria/apg/)

Please let us know if you have any additional concerns. cc @mcking65 @a11ydoer @s3ththompson

Requested publication [here](https://www.w3.org/wiki/WAI_Website_Publication_Schedule#8_December_2022)

### CODE REVIEW

**Comment by a11ydoer** [comment]
@alflennik  Do you know why this deployment is failed? The detailed deploy logs are not loading. does this imply that the change cannot be published this week unless @shawna-slh 's team do something about it?

**Comment by a11ydoer** [comment]
Great!

**Comment by shawna-slh** [comment]
@alflennik given there are issues (above), I would like to do this deployment when you are available. Denis and I are ready early. Please ping me in IRC when you are. I joined #aria-apg

**Review by shawna-slh — CHANGES_REQUESTED** [review]
This PR cannot be merged "This branch has conflicts that must be resolved"

**Comment by alflennik** [comment]
@shawna-slh Good morning, I fixed the conflict. I will message you on IRC as well.

**Comment by mcking65** [comment]
@shawna-slh how long does it take for the changes to be live once they are merged into the publication branch? I want to do some testing of redirects as soon as possible after the deploy.

**Comment by mcking65** [comment]
Oh, bummer, thx for that update.

**Comment by shawna-slh** [comment]
Sorry, that we can't deploy the build today. We've had technical problems that may take us some time to resolve given our current resources and obligations. @michael-n-cooper says he'll follow up with you.

**Comment by shawna-slh** [comment]
Data point: The WAI website deploy worked before this merge. And when this merge was reverted, and a different PR merged, the deploy worked. So it is indeed a problem with this PR.

**Comment by SteveALee** [comment]
Sorry but a bicycle crash has put me out of action for a bit. Nothing too bad. It's not obvious what problem is so will investigate next week

**Comment by alflennik** [comment]
First of all, my condolences @SteveALee, take as much time as you need to get better. Glad to hear it's nothing too bad.

About the deploy, I'm not sure if I'll be able to help since I don't know what the issue is. However, there is one issue I just fixed which might be related - I noticed the Gem lock file was missing some metadata that would allow the Gems to work on different architectures.

Do we know @shawna-slh if Steve will be able to help get this deploy over the finish line?

**Pull request merged**
