### PR TITLE
Fix 404s to html asset pages

### PR DESCRIPTION
**Pull request by alflennik**
Fixes issue https://github.com/w3c/wai-aria-practices/issues/186.

### CODE REVIEW

**Comment by howard-e** [comment]
@alflennik thanks for addressing that so quickly. Ran through the list directly and also getting to them from the application as well and it looks good for the most part but still 2 concerns here:

- [/patterns/feed/examples/feeddisplay](https://deploy-preview-187--aria-practices.netlify.app/aria/apg/patterns/feed/examples/feeddisplay)
  - The ratings icons are broken here
- [/patterns/landmarks/examples/index](https://deploy-preview-187--aria-practices.netlify.app/aria/apg/patterns/landmarks/examples/index)
  - Still 404s, but is this still a valid URL? I don't see a corresponding `.html` for this coming from `aria-practices`

**Comment by howard-e** [comment]
> * [/patterns/feed/examples/feeddisplay](https://deploy-preview-187--aria-practices.netlify.app/aria/apg/patterns/feed/examples/feeddisplay)
>   
>   * The ratings icons are broken here

@alflennik I see your [comment](https://github.com/w3c/wai-aria-practices/issues/186#issuecomment-1412186930) on now so this can be ignored.

**Comment by alflennik** [comment]
About [/patterns/landmarks/examples/index](https://deploy-preview-187--aria-practices.netlify.app/aria/apg/patterns/landmarks/examples/index), this page was renamed to general-principles.html to avoid confusion with the other pages called index.html. Do you find any references to that old page? If so you may have found a bug.

**Review by howard-e — APPROVED** [review]
LGTM

The rating icons are still broken for the feedDisplay example. It seems to be moved to an unexpected path when built on the wai-website repo but I we can follow up with a PR to fix that afterwards

**Pull request merged**
