### PR TITLE
For publication / deploy on Thursday December 12, 2024

### PR DESCRIPTION
**Pull request by howard-e**
Hi @shawna-slh and @remibetin. We would like to deploy a new version of the APG. This was approved during [this week's APG meeting](https://www.w3.org/2024/12/10-aria-apg-minutes.html#83a1) by @mcking65.

The update includes the following, sourced from [w3c/aria-practices 2024-12-12 October Publication Pull Requests Milestones](https://github.com/w3c/aria-practices/milestone/36?closed=1) and pushed to [w3c/aria-practices `main` branch](https://github.com/w3c/aria-practices/commits/main):
### Infinite Scrolling Feed Example: Add fallback foreground color ([pull #3150](https://github.com/w3c/aria-practices/pull/3150))

By Giacomo Petri on November 2, 2024

Resolves issue [#3149](https://github.com/w3c/aria-practices/issues/3149) by adding a fallback foreground color of #000 to the body element in the iframe containing the Infinite Scrolling Feed Example. Previously, the foreground color was determined by browser defaults.

[View commit ebb4476](https://github.com/w3c/wai-aria-practices/commit/ebb4476e4560f22ec9e0146acd5bb5b59e171a2a)

---

### Scrollable Listbox Example: Ad default value 'None' so first item can be focusable on load ([pull #3139](https://github.com/w3c/aria-practices/pull/3139))

By Wagner Maciel on November 19, 2024

Fixes issue [#3138](https://github.com/w3c/aria-practices/issues/3138) by adding a new value of 'None' to the list of options and focusing that option by default. This makes the example consistent with the pattern guidance.

[View commit b0c04c4](https://github.com/w3c/aria-practices/commit/b0c04c4bf4bae3d2de4b1fed893d250ec27f5de8)

---

### Multi-Thumb Slider: Add ability to move thumbs by clicking rail ([pull #3172](https://github.com/w3c/aria-practices/pull/3172))

By Jon Gunderson on December 11, 2024

Fixed issue [#3118](https://github.com/w3c/aria-practices/issues/3118).
Updates the multi-thumb slider so clicking the rail moves one of the thumbs. The thumb closest to the click is moved.
Also updates javascript code style to use const and let instead of var.

[View commit d93a99a](https://github.com/w3c/aria-practices/commit/d93a99accd3d2677e3a1c53216421f8409433a3d)

### CODE REVIEW

**Review by shawna-slh — COMMENTED** [review]
Shawn defers process and content review to @daniel-montalvo and high-level QA to @remibetin
Thanks!

**Review by remibetin — APPROVED** [review]
LGTM.

**Review by daniel-montalvo — APPROVED** [review]
Looks good to me

**Comment by remibetin** [comment]
@howard-e Published. Please QA.

cc @daniel-montalvo

**Comment by howard-e** [comment]
Thanks @remibetin @daniel-montalvo. The changes seem good to me!

cc @mcking65 @a11ydoer

**Pull request merged**
