### PR TITLE
"Read This First" Banner in Fundamentals and Design Patterns and Widgets pages

### PR DESCRIPTION
**Pull request by isaacdurazo**

### CODE REVIEW

**Review by mcking65 — APPROVED** [review]
Thank you @isaacdurazo!! From a screen reader user's perspective, perfect!!!!

I like the image:

>An illustration of a woman with a slight smile pointing to the right

It does make me wonder if the smile is doing the pointing though. :)

Perhaps we could use the following for the alt (Note that I also removed 'An' from the start):

>Illustration of a slightly smiling woman pointing to the right

**Review by alflennik — APPROVED** [review]
Looks fabulous, great work Isaac! I appreciate you figuring out how to sneak it into the build process too.

**Comment by isaacdurazo** [comment]
Thanks for the review folks. Matt I updated the alt text to be:

> Illustration of a woman with a slight smile pointing with her finger to the right

How does that sound to you?

**Comment by sinabahram** [comment]
Would be good to mention skin color so as not to "default white".

**Comment by mcking65** [comment]
> Would be good to mention skin color so as not to "default white".

Hmm, when it says "illustration", I was not imagining anything with a skin color ...just line drawing?

**Comment by isaacdurazo** [comment]
@mcking65 We were just discussing the skin color topic internally. The illustration has color and the woman has brown skin. 

We are considering including @sinabahram's suggestion. And make the Alt Text something like this:

> Illustration of a brown skin woman with a slight smile pointing with her finger to the right

What do you think?

**Comment by sinabahram** [comment]
This is great. I think gramatically, though, it should be "brown-skinned woman " or "woman  with brown skin", though I of course prefer the identifier first. Thanks for this.

**Pull request merged**
