### PR TITLE
For publication/deploy on Thursday 15 December 2022

### PR DESCRIPTION
**Pull request by alflennik**
Hi @shawna-slh and @SteveALee, this is a second try to deploy the changes which can be found here https://github.com/w3c/wai-aria-practices/pull/174. The first attempt failed to deploy for reasons that were not immediately clear.

One potentially significant change since the last attempt to deploy was an update to the Gem lock file which should improve cross-platform compatibility. Although the motivating reason for the change was to support Netlify deployments, it seems quite possible that it this change might also fix issues with deployments to WAI. If there is anything I can do to support the deployment process please don't hesitate to let me know.

As before, coordination will be needed with @deniak (see https://github.com/w3c/wai-aria-practices/issues/172 for more information).

Preview of how the site should appear is here: [aria-practices.netlify.app/aria/apg/](https://aria-practices.netlify.app/aria/apg/)

cc @mcking65 @a11ydoer @s3ththompson

### CODE REVIEW

**Comment by SteveALee** [comment]
I'll look at this tomorrow.

FyI I recently updated the gem dependencies and given github locks the target commit of a PR your local builds or review deploys might have failed due to a dependency error during bundle install. This would only happen if your PR was older than my update to main (took me by surprise) The fix would have been a merge from main as usual to update your feature branch. Or just copy the gemfile.lock

I think I looked at the deploy build fail and did not see that specific error.

The main site build does not use your gemfile or gemfile.lock but it's own identical one.

**Comment by alflennik** [comment]
@SteveALee thanks for that information, and let me know what you see when you look tomorrow, thanks.

**Comment by alflennik** [comment]
Also @SteveALee if you're able would you be able to share the error which has occurred? I might be able to save some time if the issue is indeed related to the voluminous APG changes which have occurred since the last deploy.

**Comment by SteveALee** [comment]
Sorry, I'm not likely to look at this today after all

Steve Lee
OpenDirective http://opendirective.com

**Comment by SteveALee** [comment]
This appears to be deploying just fine? I see no error.

**Comment by s3ththompson** [comment]
@SteveALee @shawna-slh could you clarify what your last two comments mean? Will it be possible to deploy today? Does your last comment mean that you have started the deploy successfully?

**Comment by shawna-slh** [comment]
Steve is not available. I was going to test it, but cannot because "This branch has conflicts that must be resolved".

**Comment by alflennik** [comment]
Hi Shawn, the merge conflicts are caused by reverting the changes after the first attempt failed. What’s on main should be considered the authoritative version and should override whatever’s currently in the publication branch.

To bring the publication in line with main, you could run commands locally like this:

```
git checkout main
git pull
git branch -D publication
git checkout -b publication
git push origin publication --force
```

Or would you like me to do it?

**Comment by shawna-slh** [comment]
> Or would you like me to do it?

Yes please thanks

**Comment by shawna-slh** [comment]
Hi @alflennik - Can we check in an an issue Friday 16 December? Easiest by phone. Please ping "shawn" in IRC (I'm in #aria-apg) or "shawna" in W3C Slack.

**Comment by SteveALee** [comment]
FYI To me a branch delete and force push are "code smell". They really should never be necessary! It's re writing history, and we don't use rebase.

The cause of the conflict can get confusing in git due to its way of doing different. But usually normal merge should sort.

For example the conflict may have been the changes I pushed to publication and a simple merge of publish to main could have resolved and fixed the broken PR (broken as there should be no conflicts)

HtH

**Comment by shawna-slh** [comment]
Hi all. Please note that with the current WAI site deploy system, the publication branch is subject to being deployed at any time.

Given the complexity of this update and the dependencies (deploy failed last time, need W3C SysTeam on hand to do re-directs immediately following deploy), we need to schedule this update when we have the right people available. I'm in working with @michael-n-cooper on that.

**Comment by howard-e** [comment]
@shawna-slh I've submitted #181 to be reviewed and then merged into `publication` as direct updates to `publication` are now protected against. Those changes should resolve these conflicts.

cc @alflennik

**Comment by shawna-slh** [comment]
Thanks @howard-e I merged PR 181. Looks like one conflict left...

**Comment by howard-e** [comment]
@shawna-slh the `main` branch commit for `wai-website-data` was on https://github.com/w3c/wai-website-data/commit/6b8dc3317ccaf36f6de61d25c66b2f554396cbda while this was on https://github.com/w3c/wai-website-data/commit/adf06a0344196c2ffff7fc0c3628cd6d37bc76ed which is the latest. 

#182 Should bring `main` to the latest and *hopefully* resolve that conflict.

**Comment by shawna-slh** [comment]
@howard-e @alflennik @michael-n-cooper @gosko
I'm sorry to report that the build failed. Log: https://app.netlify.com/sites/wai-website/deploys/63d1dd3a6e86e23612982dd7

For comparison, here's the previous that succeeded: https://app.netlify.com/sites/wai-website/deploys/63d1d29eb1221c000a923686

I'll send a zoom link for meeting at 7:00PT/9:00CT/10:00ET on Thursday 26 January to discuss...

**Pull request merged**
