### PR TITLE
For publication / deploy on Tuesday December 12, 2023

### PR DESCRIPTION
**Pull request by howard-e**
Hi @shawna-slh. We would like to deploy a new version of the APG as requested by @mcking65 through a recent email thread.

The update includes the following, as sourced from [the October 24, 2023 and December 11, 2023 w3c#aria-practices commits](https://github.com/w3c/aria-practices/commits/main):

---
### Landmark Practice: Add note to prevent dialog content wrapped in a landmark ([pull #2818](https://github.com/w3c/aria-practices/pull/2818))

By mcking65 on Oct 24, 2023

Resolve issue [#2512](https://github.com/w3c/aria-practices/pull/2512) by adding the following note to principles of landmark design:

>Note that wrapping the content of a modal dialog in a landmark region is unnecessary. A landmark that wraps modal content cannot provide any benefit to users because it is not perceivable unless the modal is open. In addition, when a modal is open, a landmark containing its content is superfluous because the modal itself is a container that provides both a name and boundaries.

[View commit eed124a](https://github.com/w3c/aria-practices/commit/9a5e55ccbeb0f1bf92b6127c9865da8426d1c864)

---

### Infrastructure: Use aria-practices repo as source for images, patterns.html, and practices.html ([pull #2869](https://github.com/w3c/aria-practices/pull/2869))

By alflennik on Dec 11, 2023

Resolve issue 2702 by moving HTML content and images from the wai-aria-practices repo into the aria-practices repo. This includes HTML content for the patterns.html page, the practices.html page, and images across all patterns and examples. A complementary change is made to the build process in the wai-aria-practices repo via PR [w3c/wai-aria-practices#280](https://github.com/w3c/wai-aria-practices/pull/280).

[View commit 4bb1946](https://github.com/w3c/aria-practices/commit/4bb1946ad10d25a504c2fe3dbfa0875fed096af9)

---

### Infrastructure: Source heading for read this first content from aria-practices repo ([pull #2867](https://github.com/w3c/aria-practices/pull/2867))

By Paul-Clue on Dec 11, 2023

Moves the h2 element that is part of the "Read This First" content from the wai-aria-practices repo into the aria-practices repo. This is part of an effort to ensure all content is sourced and controlled from the aria-practices repo and the wai-aria-practices repo provides only transformations necessary for site build.

[View commit 4a3531f](https://github.com/w3c/aria-practices/commit/4a3531f056b6f6ea322b58243f82b12def1b67cc)

---

### Modal Dialog Example: Increase z-index of dialog backdrop ([pull #2843](https://github.com/w3c/aria-practices/pull/2843))

By emamoah on Dec 11, 2023

Resolves issue 2842: A CSS bug where part of the modal dialog popup was obscured on some small screens.

[View commit d057791](https://github.com/w3c/aria-practices/commit/d05779184457932110f567d8aeb0f1645917e098)

### CODE REVIEW

**Comment by howard-e** [comment]
cc @mcking65 @a11ydoer @ccanash

**Comment by shawna-slh** [comment]
published/deployed.

**Comment by mcking65** [comment]
Thank you @shawna-slh!!

@a11ydoer @howard-e 

Please survey the production site to ensure image presentation is as expected across patterns, examples, and practices. I will verify the other changes.

**Comment by mcking65** [comment]
I have verified the changes that I can .... I can't test the z index change to modal dialog. @a11ydoer, could you do that please?

**Comment by a11ydoer** [comment]
@mcking65 Z index looks good. However, there are two h2, "Read This First" in the [dialog modal page.](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/)

**Pull request merged**
