### PR TITLE
Add auto sidebar

### PR DESCRIPTION
**Pull request by SteveALee**
Will need to delete all the old sidebars

### CODE REVIEW

**Comment by alflennik** [comment]
Hi @SteveALee maybe you can help me with this? I switched to your branch and ran `bundle install` and then `bundle exec jekyll serve` but I got the following error:

```
Dependency Error: Yikes! It looks like you don't have /Users/path/wai-aria-practices/_plugins/theme-plugin.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /Users/path/wai-aria-practices/_plugins/theme-plugin.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- nokogiri/nokogiri' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

**Comment by SteveALee** [comment]
Oh wow, will check to morrow. But bundle install should fix that error as I added a gem. Maybe delete the gem lock file and try again.

Also I'm not sure if thar serve command is good as not specifying the config file. Look in netlify.toml dev section for complete command to run. Also try the git submodules command under build in case _external/data is missing the plugin code.

For local dev I installed the netlify cli and then run "netlify dev" to build and serve.

**Comment by SteveALee** [comment]
@alflennik Sorry my badd. The netlify command build was not setup correctly. it just called your prebuild script. Now updated.

However it's a bit "chicken and egg" as the git submodules need to be fetch first before "bundle install will work". Easiest squence of commands is:

- netlify build - updates submodules - ignore GEM errors (unless about submodules)
- bundle install
- netlify dev - will build and serve (on linux/mac/WSL)

Hope that helps. I cleand my directory and just tried the esteps :)

**Comment by SteveALee** [comment]
NB! I updated some of the generated files to show what needs to be done in the transformation.

**Comment by SteveALee** [comment]
It looks like main is overlaying the sidebar so needs to have it's width reduced. Perhaps that will happen when the old sidebar is removed, if not tied to a grid?

**Review by alflennik — APPROVED** [review]

**Pull request merged**
