### PR TITLE
For publication / deploy on Tuesday May 28, 2024

### PR DESCRIPTION
**Pull request by howard-e**
We would like to deploy a new version of the APG. This was approved during the [May 21, 2024 APG meeting](https://www.w3.org/2024/05/21-aria-apg-minutes.html#t02) and during a recent email thread with @mcking65.

The update includes the following, as sourced from the [2024-05-23 APG Publication Pull Requests milestones](https://github.com/w3c/aria-practices/milestone/31?closed=1) and [recent w3c#aria-practices commits to `main`](https://github.com/w3c/aria-practices/commits/main):

## About: Add page to about section that explains the AT support tables ([pull #3000](https://github.com/w3c/aria-practices/pull/3000))
 
By Matt King on May 22, 2024
 
* Adds a page to the about section that explains AT support tables.
* Adds link to the new about AT support table page from each of the example pages that includes an AT support table.

Co-authored-by: Boaz Sender
 
[View commit 2e21c92](http://github.com/w3c/aria-practices/commit/2e21c92e07744ad019b20fdc66c569fe02d8cfcb)

---

## Feed Example: Move display of example from separate page into standard APG example page ([pull #2775](https://github.com/w3c/aria-practices/pull/2775))
 
By Ariella Gilmore on May 22, 2024
 
Enables the feed example to be displayed inline within the feed example page using an iframe. Previously, the example had to be opened in a separate page.

Also includes some editorial revisions and updates.

Co-authored-by: Andrea N. Cardona
Co-authored-by: Matt King
Co-authored-by: Mike Pennisi
Co-authored-by: Howard Edwards
 
[View commit 0e40c0d](http://github.com/w3c/aria-practices/commit/0e40c0dbe6eab6ab26268516354cee528a7099ec)

---

## Infrastructure: Update skipto.js to fix shortcut key bug for non-english keyboard layouts ([pull #2975](https://github.com/w3c/aria-practices/pull/2975))
 
By Jon Gunderson on May 22, 2024
 
* Disables shortcut key for skipto when focus is on a text input.
* When menu opens, prevents hover from triggering focus change.
* Remove hover styling when pointer leaves menu.
 
[View commit 504391a](http://github.com/w3c/aria-practices/commit/504391aa41af0fd55aedc226de200a14a94f922a)

### CODE REVIEW

**Comment by howard-e** [comment]
Drafting until confirmation can be had on https://github.com/w3c/aria-practices/pull/3026 being ready for today's publication, by 9:00 PST.

**Comment by howard-e** [comment]
@shawna-slh is there a cut off time for when you could perform the publication?

**Comment by shawna-slh** [comment]
If it is simple content updates, then I can do until 4:30pmCT. If there are potentially problematic things that might break the site deploy, I'd be hesitant to do after 12:00noonCT since Remi will be done for the day.

NOTE: For timely communications, please ping me in Slack (or IRC or WhatsApp or text) as I won't see e-mail notifications of comments here right away.

**Comment by howard-e** [comment]
> If it is simple content updates, then I can do until 4:30pmCT. If there are potentially problematic things that might break the site deploy, I'd be hesitant to do after 12:00noonCT since Remi will be done for the day.

Yep, this PR does contain only simple content updates. [1 additional page](https://deploy-preview-327--aria-practices.netlify.app/aria/apg/about/at-support-tables/) has been added but it follows the pattern of other similar pages in the About section, so it should raise no issues. And the incoming change being requested here only affects a single existing file as well.

cc @mcking65 @a11ydoer on the above time constraints if we would like to include still include https://github.com/w3c/aria-practices/pull/3026 today.

> NOTE: For timely communications, please ping me in Slack (or IRC or WhatsApp or text) as I won't see e-mail notifications of comments here right away.

Thank you for the reminder, will do!

**Comment by mcking65** [comment]
@shawna-slh 

Offline, we just started a discussion about whether to wait till Tuesday b/c of timing of AT support table update dependencies on the aria-at side.

**Comment by mcking65** [comment]
I merged w3c/aria-practices#3026

**Comment by howard-e** [comment]
> Offline, we just started a discussion about whether to wait till Tuesday b/c of timing of AT support table update dependencies on the aria-at side.

@mcking65 @shawna-slh I've updated the description of this PR to be a May 28 deploy request instead.

**Comment by shawna-slh** [comment]
@howard-e This is currently set as draft. Is it ready for deploy/publication?

**Review by shawna-slh — APPROVED** [review]

**Comment by shawna-slh** [comment]
@remibetin - ready to publish. Thanks!

**Comment by a11ydoer** [comment]
@remibetin, please let me know if it has been published so I can confirm the changes. @mcking65

**Comment by remibetin** [comment]
@a11ydoer I will publish in the next 30min.

**Comment by remibetin** [comment]
@a11ydoer @mcking65 @howard-e These changes have been published!

cc @shawna-slh

**Comment by howard-e** [comment]
Thanks @remibetin!

**Pull request merged**
