### PR TITLE
Fixes preparing website for GAAD

### PR DESCRIPTION
**Pull request by alflennik**
Addresses the following issues:

[Issue 89](https://github.com/w3c/wai-aria-practices/issues/89) - Implement Jump To
[Issue 98](https://github.com/w3c/wai-aria-practices/issues/98) - Hide the Current Work Section
[Issue 32](https://github.com/w3c/wai-aria-practices/issues/32) - Update Page Footers Date Format
[Issue 91](https://github.com/w3c/wai-aria-practices/issues/91) - Update Case of URL

### CODE REVIEW

**Comment by mcking65** [comment]
@alflennik all content changes from aria-practices have been merged to main in aria-practices.

**Review by howard-e — APPROVED** [review]
I think I'm unable to verify #91 works as intended unless deployed, as Netlify changes the URI regardless but the code changes follow what seems to be requested.

For #32, had briefly discussed a case internally where there were additional empty footers. Thanks for taking a look at that @alflennik!

LGTM

**Comment by mcking65** [comment]
nice work!!!!!!!!!!!!!

**Comment by mcking65** [comment]
@alflennik @howard-e you guys rock!

**Pull request merged**
