### PR TITLE
Updating read this first banner

### PR DESCRIPTION
**Pull request by evmiguel**

### CODE REVIEW

**Comment by richnoah** [comment]
@evmiguel thank you.

**Review by howard-e — APPROVED** [review]
Looks good!

**Review by isaacdurazo — COMMENTED** [review]
I have a little concern. Wouldn't "read this to understand why" be a link that's not descriptive on its own? which is an accessibility bad practice.

The same issue applied to the current version where we have "Read this First" as the link.

It's something that just occurred to me

**Comment by richnoah** [comment]
@isaacdurazo would you see using the aria-label attribute?  Since it is a link and there are no elements visible on the page that describe the object?

**Comment by isaacdurazo** [comment]
That's a good idea, @richnoah. So it could be something like: 

`<a href="../practices/read-me-first/" aria-label="Read this to understand why no ARIA is better than bad ARIA">read this to understand why</a>.`

@evmiguel what do you think about this?

**Comment by evmiguel** [comment]
@isaacdurazo I like the aria-label. Testing it out with VoiceOver was a good and clearer experience than before.

**Review by mcking65 — APPROVED** [review]
Thank you @evmiguel, looks great from SR user POV and editorial content POV.

**Comment by mcking65** [comment]
@isaacdurazo asked:

> I have a little concern. Wouldn't "read this to understand why" be a link that's not descriptive on its own? which is an accessibility bad practice.
> 
> The same issue applied to the current version where we have "Read this First" as the link.
> 
> It's something that just occurred to me

Isaac, You're right that it is helpful to strive for link text that is meaningful out of context. In this case, I think it is perfectly acceptable to end the link text with "why" because the most important aspect is the directive to read first. Ending with "why" would satisfy accessibility requirements. Additionally, there are no other links with similar text on the page.

That said, the aria-label that adds additional words after the "why" makes the link fully understandable outside of its context, which is a convenience for a screen reader user looking at a list of links. It has the minor downside of making the paragraph sound redundant. The link is fully accessible with or without the aria-label. I do not know which is better in practice.

**Pull request merged**
