### PR TITLE
For publication / deploy on Tuesday August 6, 2024

### PR DESCRIPTION
**Pull request by howard-e**
Hi @shawna-slh. We would like to deploy a new version of the APG. This was approved during the [July 30, 2024 APG meeting](https://www.w3.org/2024/07/30-aria-apg-minutes.html#t02).

The update includes the following, as sourced from the [2024-08-06 APG publication pull requests for August 6, 2024 milestones](https://github.com/w3c/aria-practices/milestone/32?closed=1) and [recent w3c#aria-practices commits to `main`](https://github.com/w3c/aria-practices/commits/main):

## Patterns page: Add patterns filter and grid/list view toggles ([pull #3043](https://github.com/w3c/aria-practices/pull/3043))
 
By Stalgia Grigg on July 30, 2024
 
This PR includes two new features for the patterns page:
1. A text input that filters the displayed patterns as the user types.
2. Options for choosing between a grid view (the default) or a more compact list view.
 
[View commit 8e5825a](http://github.com/w3c/aria-practices/commit/8e5825a2543cf503b62c0558d480290dab66a02f)

---

## Infrastructure: Add special Treatment of Examples Marked 'Experimental' ([pull #2977](https://github.com/w3c/aria-practices/pull/2977))
 
By Alexander Flenniken on July 28, 2024
 
Provides the infrastructure to treat example pages marked as experimental differently from other example pages as defined in issue [#2836](https://github.com/w3c/aria-practices/issues/2836):
1. A different "Read This First" section that is expanded by default is inserted into experimental example pages.
2. Experimental example pages are excluded from the main index tables and listed in a separate section at the bottom of the index page.

Experimental example pages are identified by a data attribute on the main element as defined in issue [#2836](https://github.com/w3c/aria-practices/issues/2836). 

Co-authored-by: Stalgia Grigg
Co-authored-by: Matt King
 
[View commit 2a2e148](http://github.com/w3c/aria-practices/commit/2a2e1484c90063f1bd72f52594e4e7d41c39daf8)

---

## All Example Pages: Add source copy instructions and CodePen button to HTML source section ([pull #3041](https://github.com/w3c/aria-practices/pull/3041))
 
By Ariella Gilmore on July 27, 2024
 
Resolve issue [#3027](https://github.com/w3c/aria-practices/issues/3027) with the following changes:
1. Direct readers to copy HTML source from codepen instead of from the example page.
2. Add an additional codepen button adjacent to the directions.

Note that if users copy the source directly from the example page, the code may not work as designed because of spacing differences between the HTML source file and the formatting of the source code for display within the web page. Thus, this change instructs users to open the source in codepen where the original spacing is preserved. It makes doing so easy by providing a codepen button adjacent to the instructions. 

Co-authored-by: Matt King
 
[View commit b28a984](http://github.com/w3c/aria-practices/commit/b28a984eef2669c5809444222babe39c7fe72ca9)

---

## Coverage and Quality Report: Add reporting on use of forced-colors media query and currentcolor value ([pull #3024](https://github.com/w3c/aria-practices/pull/3024))
 
By Jon Gunderson on July 23, 2024
 
Revised the coverage and quality report script to:
* Change section "Graphics Techniques" to "SVG and High Contrast Techniques".
* Remove information about use of forced-color-adjust.
* Add information about use of forced-colors media query.
* Add information about use of currentcolor value for CSS properties that support color values.
* remove information about use of CSS :before, :after and content. 

Co-authored-by: Matt King
 
[View commit cb74ba2](http://github.com/w3c/aria-practices/commit/cb74ba2d812a07779f83119459f2289bb3d29f96)

---

## Ratings Slider: Use buttontext instead of linktext system color in high contrast mode ([pull #3025](https://github.com/w3c/aria-practices/pull/3025))
 
By Jon Gunderson on July 23, 2024
 
[View commit 19347dd](http://github.com/w3c/aria-practices/commit/19347dd2211e743afcf3962c0ced13b5987fd86d)

### CODE REVIEW

**Comment by howard-e** [comment]
cc @mcking65 @a11ydoer

**Comment by daniel-montalvo** [comment]
Tagging @remibetin as well, who will now be helping with publications.

**Review by shawna-slh — APPROVED** [review]

**Comment by shawna-slh** [comment]
Approved. @remibetin Please publish. Thanks!

**Comment by remibetin** [comment]
@daniel-montalvo @howard-e This PR has been merged and published. You can now check everything is as intended.

cc @shawna-slh

**Pull request merged**
