### PR TITLE
For publication / deploy on Tuesday October 29, 2024

### PR DESCRIPTION
**Pull request by howard-e**
Hi @shawna-slh and @remibetin. We would like to deploy a new version of the APG. This was approved during [last week's APG meeting](https://www.w3.org/2024/10/22-aria-apg-minutes.html#9b53) by @mcking65.

The update includes the following, sourced from [w3c/aria-practices 2024-10-29 October Publication Pull Requests Milestones](https://github.com/w3c/aria-practices/milestone/35?closed=1) and pushed to [w3c/aria-practices `main` branch](https://github.com/w3c/aria-practices/commits/main):

### Tooltip Pattern: Clarify mouseout dismissal behavior ([pull #3140](https://github.com/w3c/aria-practices/pull/3140))

By Adam Page on October 15, 2024

Resolve issue [#3109](https://github.com/w3c/aria-practices/issues/3109) by clearly stating that the tooltip should remain open as long as the pointer is over the tooltip.

[View commit a6f3fbe](https://github.com/w3c/wai-aria-practices/commit/a6f3fbe390469ff745a1f346aaaa3fce60f1a1a1)

---

### Acknowledgements Page: Update W3C Staff Editors ([pull #3143](https://github.com/w3c/aria-practices/pull/3143))

By Daniel Montalvo on October 15, 2024

Add daniel-montalvo and move Michael Cooper to previous editors.

[View commit 15b2c6c](https://github.com/w3c/aria-practices/commit/15b2c6c5fb05dc7e495efd9ed85db7c94f2db650)

---

### All Example Pages: Update links to related Issues ([pull #3123](https://github.com/w3c/aria-practices/pull/3123))

By Howard Edwards on October 22, 2024

Fixes issue [#3113](https://github.com/w3c/aria-practices/issues/3113).

The links to "related issues" on each example page point to a GitHub project. There is a seprate GitHub project for each pattern or group of similar patterns.

The sunset of classic GitHub projects resulted in redirects from classic project URLs to the new migrated project URLs. This PR changes the links to point directly to the new project pages.

Co-authored-by: Matt King

[View commit 265f408](https://github.com/w3c/aria-practices/commit/265f4081295cf04c916094601c1dd558fab5ee3c)

### CODE REVIEW

**Comment by howard-e** [comment]
cc @mcking65 @a11ydoer @ccanash

**Comment by remibetin** [comment]
@howard-e Looks good to me.

**Review by shawna-slh — APPROVED** [review]
Thank you for the clear information @howard-e 

From quick skim, looks OK to me. Over to you, @remibetin

**Comment by remibetin** [comment]
@howard-e Published. Please QA.

**Pull request merged**
