### PR TITLE
For publication/deploy on Thursday 13 October 2022

### PR DESCRIPTION
**Pull request by s3ththompson**
This PR includes the following PRs which landed on w3c/aria-practices and were automatically committed to this repo (the website repo):

- Skipto update and removing jumpto.js [w3c/aria-practices#2402](https://github.com/w3c/aria-practices/pull/2402)
- Switch Example using Button: Fix white on white bug [w3c/aria-practices#2482](https://github.com/w3c/aria-practices/pull/2482)
- Acknowledgements: Add Carolyn MacLeod as honorary editor [w3c/aria-practices#2500](https://github.com/w3c/aria-practices/pull/2500)

cc @shawna-slh we are hoping to deploy this PR before the publication freeze on October 14. We don't expect to need any technical assistance from Steve.

Please let us know if you have any additional concerns. cc @mcking65 @alflennik @a11ydoer 

Edit: requested publication [here](https://www.w3.org/wiki/WAI_Website_Publication_Schedule#13_October_2022)

### CODE REVIEW

**Comment by shawna-slh** [comment]
Hi @s3ththompson and all. I can certainly publish this next Thursday. Would you like me to publish it sooner, or would you like it to wait until Thursday?

**Comment by s3ththompson** [comment]
@shawna-slh We'd be happy to merge at your earliest convenience! I was hoping to open this PR in time for a deploy yesterday, but I didn't make it in time. Thanks!

**Comment by shawna-slh** [comment]
Published. I did a quick look around and things look OK to me.

I had another update I wanted to publish today, so easy to add it. Feel free to ask if I can publish other than Thursdays. I have time reserved on Thursday mornings, yet I can usually fit it in another time if useful.

**Comment by mcking65** [comment]
Thank you @shawna-slh!

**Pull request merged**
