### PR TITLE
For publication / deploy on Tuesday October 2, 2023

### PR DESCRIPTION
**Pull request by howard-e**
Hello @shawna-slh. We would like to deploy a new version of the APG as requested by @mcking65 through a recent email thread.

The update includes the following, as sourced from [Status of Site Updates > Changes ready for next publication](https://github.com/w3c/aria-practices/wiki/September-26%2C-2023-Agenda) and [October 2, 2023 w3c#aria-practices commits](https://github.com/w3c/aria-practices/commits/main):

---

### Listbox Examples: Update scrolling of listbox item with focus into view when page is magnified ([pull #2622](https://github.com/w3c/aria-practices/pull/2622))

By jongund on Sep 18, 2023

In the listbox examples, fixes [#2545](https://github.com/w3c/aria-practices/issues/2545) with the following changes:
* Updated code to scroll the element referenced by @aria-activedescendant@ into view when view is magnified
* Updated accessibility features documentation in support of this change.

While fixing this bug, the following additional changes were also made to improve code quality and implement the latest APG code guide practices:
* Use `event.key` instead of `event.keyCode` for identifying keyboard commands.
* Use `class` constructors instead of `prototype`.
* Changed `mousedown` event to `pointerdown` event to support mobile devices.
* Provide  high contrast focus ring around option referenced by `aria-activedescendant`.
* Fix bugs in keyboard support for the toolbar
* Update documentation to improve consistency with current editorial practices

Co-authored-by: Matt King <a11yThinker@gmail.com>
Co-authored-by: Mike Pennisi <mike@mikepennisi.com>
Co-authored-by: Aleena <55119766+aleenaloves@users.noreply.github.com>
Co-authored-by: Howard Edwards <howarde.edwards@gmail.com>

[View commit eed124a](https://github.com/w3c/wai-aria-practices/commit/eed124a72cc94bf0e2d39b6d33af563966f23ee1)

---

### Treegrid Pattern keyboard section: Correct text for Control + Home/End ([pull #2779](https://github.com/w3c/aria-practices/pull/2779))

By andrewnicols on Sep 18, 2023

For Control+Home and Control+End, The text in the treegrid pattern differed from the text in the treegrid
example. The text in the treegrid pattern didn't make sense because a column only contains one cell so moving focus to the first cell in a column is meaningless. The behaviour and text on the example page are consistent and make logical
sense. This commit makes the pattern and example pages consistent with each other.

Inaccurate text:
If focus is on a cell, moves focus to the first cell in the column.
If focus is on a cell, moves focus to the last cell in the column.

Corrected text:
If focus is on a cell, moves focus to the cell in the first row in the same column as the cell that had focus.
If focus is on a cell, moves focus to the cell in the last row in the same column as the cell that had focus.

[View commit 3b17ee7](https://github.com/w3c/aria-practices/commit/3b17ee7569e053941fd1347c4c49fd08052fb624)

---

### Navigation Treeview Example: Correct typo: change 'an' to 'and' in accessibility features ([pull #2776](https://github.com/w3c/aria-practices/pull/2776))

By sdvg on Sep 18, 2023

Incorrect text:

>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused an other elements.

Corrected text:

>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused and other elements.

[View commit 1f2e462](https://github.com/w3c/aria-practices/commit/1f2e4620b8495bc076c695f4a8f23c56f785b5ae)

---

### 11 Example pages: Fix typo in accessibility features: change 'an' to … ([pull #2803](https://github.com/w3c/aria-practices/pull/2803))

By mcking65 on Sep 20, 2023

Replace 'an' with 'and' in the accessibility features description of high contrast support of focus indicator in 11 examples.

Incorrect text:

>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused an other elements.

Corrected text:

>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused and other elements.

Examples changed:
* combobox/examples/combobox-autocomplete-both.html
* combobox/examples/combobox-autocomplete-list.html
* combobox/examples/combobox-autocomplete-none.html
* disclosure/examples/disclosure-faq.html
* disclosure/examples/disclosure-image-description.html
* menu-button/examples/menu-button-actions-active-descendant.html
* menu-button/examples/menu-button-actions.html
* menu-button/examples/menu-button-links.html
* menubar/examples/menubar-navigation.html
* switch/examples/switch-checkbox.html
* switch/examples/switch.html

[View commit a92b380](https://github.com/w3c/aria-practices/commit/a92b380910cc88e8889bd2422e560b2ae3f15410)

---

### Developing a Keyboard Interface Practice ([pull #2805](https://github.com/w3c/aria-practices/pull/2805))

By davidlj95 on Sep 20, 2023

Add missing `kbd` element to macOS re-do command in 'Key Assignment Conventions for Common Functions'

[View commit 7b0b4d3](https://github.com/w3c/aria-practices/commit/7b0b4d39986424deb062b3e3487c233b9da797e8)

---

### Multiple Combobox Examples: Adjust input height so text is fully visible in Safari on iOS ([pull #2780](https://github.com/w3c/aria-practices/pull/2780))

By andreancardona and ariellagilmore on Oct 2, 2023

Resolves [#2778](https://github.com/w3c/aria-practices/issues/2778) by revising CSS for the following 4 combobox examples so that the space for the input is tall enough to fit the text when viewed in Safari on iOS. Previously, the tops of the letters were chopped off.
* Editable Combobox With Both List and Inline Autocomplete
* Editable Combobox With List Autocomplete
* Editable Combobox without Autocomplete
* Editable Combobox with Grid Popup

[View commit 2b619c1](2b619c14b45ef0a566e91219bb3eef195b62b776)

---

### About Section: Add a page about contributing and APG TF membership ([pull #2734](https://github.com/w3c/aria-practices/pull/2734))

By mcking65 on Oct 2, 2023

Resolves [#2706](https://github.com/w3c/aria-practices/issues/2706) by adding a new page providing instructions for contributing to the APG. It describes each of the contribution channels and describes how to utilize each of them.

Co-authored-by: Jon Gunderson <jongund@illinois.edu>
Co-authored-by: Daniel Montalvo <49305434+daniel-montalvo@users.noreply.github.com>
Co-authored-by: JaEun Jemma Ku <a11ydoer@gmail.com>

[View commit 7fb7c8e](7fb7c8e28b55a2804bda682c36945a1154d1096a)

### CODE REVIEW

**Comment by howard-e** [comment]
cc @mcking65 @a11ydoer @ccanash

**Comment by shawna-slh** [comment]
Thank you for the clear documentation of the changes!

Looks like this is a new file: https://deploy-preview-268--aria-practices.netlify.app/aria/apg/about/contributing/

In case I forget, let's check it gets added properly. I might need to do an extra step.

**Comment by daniel-montalvo** [comment]
@shawna-slh These are all routine changes but indeed that's a *new* "Contributing" page. Thus the new file.

Thanks for flagging this so that we are all in the same page.

**Comment by shawna-slh** [comment]
Published/deployed.

https://www.w3.org/WAI/ARIA/apg/about/contributing/ is there.

**Comment by a11ydoer** [comment]
Thanks, @shawna-slh !!

**Pull request merged**
