### PR TITLE
Launch fixes

### PR DESCRIPTION
**Pull request by alflennik**
Addresses a number of issues such as the following:

- [Issue 26](/w3c/wai-aria-practices/issues/26)
- [Issue 28](/w3c/wai-aria-practices/issues/28)
- [Issue 31](/w3c/wai-aria-practices/issues/31)
- [Issue 46](/w3c/wai-aria-practices/issues/46)
- [Issue 49](/w3c/wai-aria-practices/issues/49)
- [Issue 56](/w3c/wai-aria-practices/issues/56)
- [Issue 59](/w3c/wai-aria-practices/issues/59)
- [Issue 48](/w3c/wai-aria-practices/issues/48)
- [Issue 47](/w3c/wai-aria-practices/issues/47)
- [Issue 52](/w3c/wai-aria-practices/issues/52)
- [Issue 66](/w3c/wai-aria-practices/issues/66)
- [Issue 55](/w3c/wai-aria-practices/issues/55)
- [Issue 76](/w3c/wai-aria-practices/issues/76)
- [Issue 65](/w3c/wai-aria-practices/issues/65)
- [Issue 53](/w3c/wai-aria-practices/issues/53)
- [Issue 32](/w3c/wai-aria-practices/issues/32)
- [Issue 58](/w3c/wai-aria-practices/issues/58)
- [Issue 60](/w3c/wai-aria-practices/issues/60)
- [Issue 79](/w3c/wai-aria-practices/issues/79)
- [Issue 74](/w3c/wai-aria-practices/issues/74)
- [Issue 24](/w3c/wai-aria-practices/issues/24)

As well as some other miscellaneous polish and build system tweaks to support deploying to the WAI website.

### CODE REVIEW

**Comment by mcking65** [comment]
Awesome progress @alflennik!!

Fixes for #26, #28, #31, #46, #49 #56, and #59 look good.

It looks like most of #24 is done; just have to get the DOM position and aria-label fixed. I commented in that issue for Steve.

I see that a97f69a is titled "Address issue 47". Unfortunately, the name I see on the top-level navigation region in the preview is still named "Context for this document". Per the conversation in #47, I thought addressing 31 would address 47 once the latest template is integrated. As you have marked this PR WIP, assuming that is still in progress.

Progress on #48 is looking awesome!

I see there are dates at the end of main on example pages. Most of the dates are much more recent than I would expect.

**Comment by alflennik** [comment]
@SteveALee I did try to add `type_of_guidance` to `_config.yml` but it didn't work for me. I did restart the server after making the change, but no luck.

**Comment by SteveALee** [comment]
@alflennik That's a shame - a lot of editing otherwise
Would normally insert here - https://github.com/w3c/wai-aria-practices/blob/main/_config.yml#L48 for all files

**Comment by alflennik** [comment]
Thanks for confirming the fixes @mcking65 that's appreciated!

Regarding the dates in the footer of example pages, I've set it up to use the latest commit date for the example html file. The most recent change for most of the examples was triggered by [a PR made by Simon](https://github.com/w3c/aria-practices/pull/2069) which updated the HTML markup for 73 files on Nov 23, 2021.

**Comment by mcking65** [comment]
@alflennik 

> Regarding the dates in the footer of example pages, I've set it up to use the latest commit date for the example html file. The most recent change for most of the examples was triggered by [a PR made by Simon](https://github.com/w3c/aria-practices/pull/2069) which updated the HTML markup for 73 files on Nov 23, 2021.

Would it be possible for us to exclude certain commits from the last updated date calculation by looking for a label on the PR? That is, can the update date calculation code get the PR associated with each commit, get the labels on the PR, and look for a specific label? If that label exists, ignore that commit and look for the next earlier commit? Then we could add a label like "non-substantive-change" to any PR and the commit to main for that PR would be ignored by the update date calculation.

I'd like to exclude that specific PR from the date calculation, and I am sure there are others that should be excluded, and there will be more in the future. The update date should reflect only substantive changes, otherwise it won't be very useful.

**Comment by mcking65** [comment]
Fixes for issue #66 look good.

**Comment by mcking65** [comment]
Unfortunately, we have a regression in the fix for #26. There is only one skip to, but it is the static skip to main link from the template rather than the APG jumpto menu.

**Comment by mcking65** [comment]
@alflennik, thank you for the additional pushes this evening!! I have confirmed resolution for 13 of the issues now!!

**Pull request merged**
