### PR TITLE
For publication / deploy on Tuesday 28 February 2023

### PR DESCRIPTION
**Pull request by alflennik**
Hi @shawna-slh, we would like to deploy the following changes and fixes to ARIA Practices:

- Includes https://github.com/w3c/aria-practices/pull/2597 which fixes https://github.com/w3c/wai-aria-practices/issues/186
- Includes updates to aria-practices dependencies e.g. glob, cspell, cheerio and others.
- Includes new Prettier code formatting for aria-practices assets.

@deniak As we did in a previous deploy, we will need to change the redirects at the same time we deploy the site. The changes are below. Big thanks for your help.

REMOVE the following redirects which already exist (from / to):

```
https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/datagrids.html
https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/layoutgrids.html
https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/HTML5.html https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/html5
https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/index.html https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/index
```

ADD new redirects as follows (from / to):

```
https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/data-grids.html
https://www.w3.org/WAI/ARIA/apg/example-index/grid/datagrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/data-grids.html
https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/layout-grids.html
https://www.w3.org/WAI/ARIA/apg/example-index/grid/layoutgrids.html https://www.w3.org/WAI/ARIA/apg/example-index/grid/layout-grids.html
https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/html5 https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/HTML5.html
https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/index.html https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/index https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html
```

cc: @mcking65 @a11ydoer

### CODE REVIEW

**Comment by shawna-slh** [comment]
@gosko and @deniak -- since this is a 404 fix, I'd like to publish soon. Please ping me in IRC or Slack if you are able to do redirects Thursday 23 Feb or Friday. Thanks!

**Comment by deniak** [comment]
@shawna-slh I can take care of those today. Let's sync on irc.

**Comment by shawna-slh** [comment]
deployed. quick skim looks like worked as expected, e.g.,
https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/dataGrids/ 404
https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/ in place

**Comment by shawna-slh** [comment]
@alflennik Please confirm it's OK from your perspective. @deniak will do redirects in a couple minutes.

**Comment by deniak** [comment]
Some of the targets listed above are still returning 404s, e.g.:
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/data-grids.html
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/layout-grids.html
* https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/HTML5.html

**Comment by deniak** [comment]
Here are the redirects I ended up implementing:
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html -> https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/LayoutGrids.html -> https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/
* https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/index.html -> https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/datagrids.html -> https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/
* https://www.w3.org/WAI/ARIA/apg/example-index/grid/layoutgrids.html -> https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/
* https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/html5 -> https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/HTML5.html
* https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/index -> https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/general-principles.html

Let me know if it needs to be updated.

**Comment by mcking65** [comment]
Thank you @alflennik, @shawna-slh, and @deniak! All the errors with previously saved locations except for one are fixed!!

There is one page where the left side of the redirect does not match what I have as the previous location. I saved bookmarks to every page in the APG immediately after launch last May. For the Landmarks HTML5 sectioning page, the prior location I have is:

https://www.w3.org/WAI/ARIA/apg/example-index/landmarks/HTML5.html

That still yields a 404. Note the uppercase in the file name.

It should redirect to:
https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/HTML5.html

Perhaps this should be an additional redirect rather than a change to the existing redirect.

**Comment by gosko** [comment]
Hi @mcking65, I updated the redirect to use HTML5.html instead of html5 after confirming there were no recent requests in our logs for the html5 version.

**Comment by mcking65** [comment]
Wow! thank you @gosko for that amazing turn-around!!

I verified that it works. I'm now confident that we have redirects in a good status for all pages impacted by the redesign and restructure work.

**Pull request merged**
