### PR TITLE
Get grid combobox example working

### PR DESCRIPTION
**Pull request by SteveALee**
Browse to http://localhost:8888/ARIA/apg/example-index/combobox/grid-combo.html

I'll try to get preview working - difficult as not to main branch :(

### CODE REVIEW

**Comment by SteveALee** [comment]
@alflennik here's a preview - https://627d39c45f78a7075bf12c18--wai-aria-practices2.netlify.app/aria/apg/example-index/combobox/grid-combo

**Comment by SteveALee** [comment]
and FYI here it is in the context of the full site preview 

https://627d3ca09a7d2e005648ca54--wai-website.netlify.app/aria/apg/example-index/combobox/grid-combo

**Comment by mcking65** [comment]
@SteveALee,

Is it expected that some links do not work in this preview?

**Comment by SteveALee** [comment]
Yes indeed

Only the [aria/apg/example-index/combobox/grid-combo](https://627d3ca09a7d2e005648ca54--wai-website.netlify.app/aria/apg/example-index/combobox/grid-combo) example has correct URIs defined in permalinks - leaving rest to Alex :)

**Pull request closed without merging**
