### PR TITLE
Update to use `W3CGRUNTBOT_TOKEN` in workflow in place of `GH_TOKEN`

### PR DESCRIPTION
**Pull request by howard-e**

### CODE REVIEW

**Comment by daniel-montalvo** [comment]
Thanks @howard-e 

Tagging @remibetin  and @shawna-slh for their review.

This is not content, we're just updating a Personal Access Token.

**Comment by shawna-slh** [comment]
Rémi is off the rest of this week. Should be able to address it early next week.

**Review by shawna-slh — COMMENTED** [review]
leaving to Rémi :)

**Review by remibetin — APPROVED** [review]

**Comment by howard-e** [comment]
Hi @remibetin I see a self-review after the approval. Is there a follow up review to still be done? Or can I actually merge this when I'm ready?

**Review by remibetin — APPROVED** [review]

**Pull request merged**
