### PR TITLE
For publication / deploy - Landmarks Pattern and Dialog Example Updates

### PR DESCRIPTION
**Pull request by alflennik**
Hi @shawna-slh, we would like to deploy a new version of the APG which includes a new landmarks pattern and updates to the dialog example. It's already part of the way into Tuesday, which is the day we do deploys, so apologies for requesting a bit late. If there is a chance we could deploy this week, that would be fantastic.

List of changes since April 13 deploy follows.

### Grid Pattern: Fix typos (capitalization) (pull #2701)

By icecream17 on 2023-06-05

* capitalization consistency: [-c][+C]ontrol + End
* lowercase Up ("one cell [-U][+u]p" x3)

[View commit c0054c2d](http://github.com/w3c/aria-practices/commit/c0054c2dcc32b00e2b9d0375e8a7b58201bbfd87)

### Read Me First: Remove reference to Internet Explorer in browser support section (pull #2683)

By jugglinmike on 2023-06-06

Per consensus of the 2023-04-25 meeting of the ARIA Authoring
Practices Task Force (https://www.w3.org/2023/04/25-aria-apg-minutes.html), remove mention of Internet Explorer from the browser support section.

[View commit ca63ddf0](http://github.com/w3c/aria-practices/commit/ca63ddf0f313d96301cd0f4a91b55d2e2535d647)

### Datepicker Modal Dialog: Fixed next/prev month bug and improve adherence with APG code style guide (pull #2643)

By Jon Gunderson on 2023-06-06

This PR complements PR #2618 to provide the remaining changes to resolve issue #2581.

This PR changes behavior of commands for next and previous month and year In the date picker dialog when the currently focused date does not exist in the previous or next month or year. With these changes, if the same day number does not exist in the newly displayed month, the last day of the newly displayed month receives focus.

In addition to the above enhancement, this PR also includes the following changes:
* Updates coding practices to use `class` constructor and pointer events
* Updates documentation of page up and page down commands
* Updates regression tests for page up and page down commands

---------

Co-authored-by: Matt King <a11yThinker@gmail.com>

[View commit 32c7ef25](http://github.com/w3c/aria-practices/commit/32c7ef25b13cb8ccc0d7ea12a9df8c2e2c3a5326)

### Add landmark pattern page (pull #2670)

By Matt King on 2023-06-08

Resolves issue #2645 by adding a new page that describes landmarks as a pattern.
The pattern page references the landmarks practice for information about each of the landmark types.
Now, readers will find landmark information on both the practices and patterns pages.

[View commit fec70323](http://github.com/w3c/aria-practices/commit/fec7032399028f3c3a17dbd05253e3140e0805d2)

### Hiding Semantics Practice Page: Add missing word "that" (pull #2704)

By Paul BROWN on 2023-06-10

Editorial correction to add a missing word and missing comma.

---------

Co-authored-by: Matt King <a11yThinker@Gmail.com>

[View commit 08fee221](http://github.com/w3c/aria-practices/commit/08fee221a0dba672ccb8e189b000679870d749fd)

### Layout Grid Example 3: Remove link to archived ARIA FAQ page (pull #2721)

By Daniel Montalvo on 2023-06-10

[View commit b61ac05c](http://github.com/w3c/aria-practices/commit/b61ac05ce38327c37f521d4367f7fceef455e4bf)

### Landmark examples: Update links to related documents and SkipTo script  (pull #2624)

By Jon Gunderson on 2023-06-10

Minor editorial and code maintenance changes to all landmark example pages:

* updated SkipTo script to version 5.2
* Modify Skipto script tag to use new configuration data parameter
* updated URL targets in links to two related resources
* Update copyright date

---------

Co-authored-by: Matt King <a11yThinker@gmail.com>

[View commit 4adb78ea](http://github.com/w3c/aria-practices/commit/4adb78ea96b22db559577aa6ed64c9059596ab4a)

### CODE REVIEW

**Comment by alflennik** [comment]
Failing checks are due to Netlify's struggle with Git Submodules - I verified that the preview site is working properly and we should be good to go.

**Comment by shawna-slh** [comment]
Hi @alflennik

Friendly reminder that [Updating WAI Website Resources](https://wai-website-theme.netlify.app/workflow/) says:
-	If other than a simple content update, coordinate with Shawn at least the week before.
-	If a simple content update, then by Monday midnight US Eastern time.

And:
-	Include a brief summary of the changes. Explain everything that the website manager and/or technical lead needs to particularly be aware of.
-	Include a link to the Task Force and/or Working Group approval to publish.

Given the history of issues, I think we need to consider this more than a simple update, especially since this PR is failing checks. Why are some PRs passing check and some not? I would be much more comfortable if the PR passed checks.

Given history of issues, unless the checks are all passing and indeed it is just simple content edits, then let’s schedule time for me to publish when you are available in case there are problems.

**Comment by mcking65** [comment]
@alflennik  @shawna-slh 

We might have a couple more PRs merged into aria-practices:main by Monday. Would we be able to add them to the deploy. One is an update to the skipto script and the other is a simple editorial correction:
* w3c/aria-practices#2724
* w3c/aria-practices#2680

**Comment by shawna-slh** [comment]
> Shawn said she will release the changes next Tuesday.

Sorry, not quite. I said:
> ... Why are some PRs passing check and some not? I would be much more comfortable if the PR passed checks.

Please would you look into this more.

And:
> Given history of issues, unless the checks are all passing and indeed it is just simple content edits, then let’s schedule time for me to publish when you are available in case there are problems.

We'd need to schedule a specific time.

<hr>

> Would we be able to add them to the deploy?

Sure, as long as they are sufficiently tested and approved. And ideally all checks pass and the preview works. :-)

**Comment by howard-e** [comment]
> ... especially since this PR is failing checks. ...

Hi @shawna-slh. I'm thinking some form bad caching + de-sync with Netlify may have happened here. When Netlify was doing the `preparing the repo` step, the error that was initially shown is:

> fatal: remote error: upload-pack: not our ref cf01cbd9eed167a0ffe96ec2371c1d915271f535

The commit ref doesn’t seem to exist in either `aria-practices` or `wai-aria-practices` so we're unsure what it's trying to reference here (it may have been some removed commit, or coming from a private repo, etc) so we figured this may have been some caching hiccup.

We’ve rebuilt the `aria-practices.netlify.app` by doing a `clear cache and retry with latest commit` for this PR (and would suggest the same be done for the `wai-aria-practices2.netlify.app` build). And it now displays the build as passing in our [Netlify logs](https://app.netlify.com/sites/aria-practices/deploys/648b6fc27d0ff406662e32b5) and that is also reflected in the [auto-generated Netlify comment in this PR](https://github.com/w3c/wai-aria-practices/pull/227#issuecomment-1589671807) but the same isn’t reflected in the build status of this PR. So some de-sync may have happened here in Netlify reflecting the updated state of `main`, when used as the head ref in a PR.

> Why are some PRs passing check and some not? I would be much more comfortable if the PR passed checks.

For PRs #228, #230 and #231, the same `not our ref error` is reflected in the logs for `wai-aria-practices2.netlify.app` but not `aria-practices.netlify.app`, as that builds successfully for the noted PRs and is reflected in the PRs' statuses and also in the generated Netlify comments.

I'd think that doing a `clear cache and retry with the latest commit` on those PRs for `wai-aria-practices2.netlify.app`, and verifying that it builds successfully should address that.

**Comment by shawna-slh** [comment]
> clear cache and retry with the latest commit

Done on wai-aria-practices2
Maybe this means it's OK? https://app.netlify.com/sites/wai-aria-practices2/deploys/648ba0628fa469046df3b45e

> For a proper green check, it may be good to also re-do this publication PR...

+1

Thanks.

**Comment by shawna-slh** [comment]
> We'd need to schedule a specific time.

@alflennik @howard-e 

Does Tuesday 20 June at 10:30 CT work for you?

**Comment by ccanash** [comment]
Hi @shawna-slh , would it be possible to schedule this for a little later, 12:30 CT? The team is already offline for the weekend and we have Juneteenth off so we they will be back on online Tuesday morning. Thank you

**Comment by shawna-slh** [comment]
I am setting a few things up, and will get to this soon. ~10 minutes...

**Comment by shawna-slh** [comment]
deploy seems to have worked fine! Please check live site and let me know if all good...

**Comment by shawna-slh** [comment]
/me checks https://github.com/w3c/aria-practices/commit/ca63ddf0f313d96301cd0f4a91b55d2e2535d647 is indeed live at https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/

**Comment by mcking65** [comment]
I have verified all the fixes in production.

**Pull request merged**
